apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: theopen4/backend-udapeople:v1
        ports:
        - containerPort: 8080
        envFrom:  
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secrets
           