version: "3"
services:
  reverseproxy:
    build:
      context: ./reverseproxy-udapeople
    image: reverseproxy-udapeople
  backend_user:
    build:
      context: ./backend
    image: backend-udapeople
  frontend:
    build:
      context: ./frontend
    image: frontend-udapeople
