version: "3"
services:
  backend-udapeople:
    build:
      context: ./backend
    image: backend-udapeople
  frontend-udapeople:
    depends_on:
      - backend-udapeople
    build:
      context: ./frontend
    image: frontend-udapeople
